spring:
  application:
    name: dubbo-provider-service
dubbo:
  scan:
    basePackages: io.github.wukn.demo.dubbo.service
  application:
    id: dubbo-provider-service
    name: dubbo-provider-service
  registry:
    id: zookeeper
    address: zookeeper://localhost:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 8081
  monitor:
    address: zookeeper://localhost:2181
    